### ISSUE TITLE
missing error(nil) from XML()

### ISSUE THREAD

**Issue by figlief** [agrison/go-tablib#1]
the XML() function only returns one value when there is no error it should of course return a nil error.

xml, err := ds.XML() is impossible at the moment.

**Comment by figlief** [comment]
ok i get it. XML() doesn't produce errors so doesn't need to return an error.

however, I think it would better if it had the same signature as eg JSON(), CVS(),  YAML()

**Comment by agrison** [comment]
Actually `mxj` the lib used for xml rendering can produce errors on call to `XmlIndentWriter`, so I will propagate them as errors if any occurs, so that the signature for `XML()` will be the same as the other export formats.
